### ISSUE TITLE
Session empty

### ISSUE THREAD

**Issue by letsbelopez** [junaid33/shopify-next#1]
@junaid33 thanks for making this boilerplate. I was trying to build something similar, and ended up find your repo somehow. NextJS is great. It's my first time using it.

Have you noticed that the root url with the shop query parameter doesn't take you to the Shopify App install page? I built a Koa server outside of next and this seemed to be the default behavior. Anyways if you know of the fix to install the app, I'd be happy to help implement it.

**Comment by junaid33** [comment]
Hey man! Glad you liked it but it's actually mostly from this repo:

https://github.com/DimensionSoftware/generator-shopify-nextjs/tree/master/generators/app/templates

So the way to install the app on your store is to navigate to /install. That will give you a form to fill out and click install. This will redirect you to the store to install the app and then redirect you back to your app. You should see the access token and shop. Let me know if you need anymore help! I was in the same situation as you a few weeks ago :)

**Comment by letsbelopez** [comment]
Thanks for the response. I was able to get the app installed on the store. 

But it seems like it's having trouble remembering it was installed though. Maybe the session isn't remembering the session long enough? To get access to the store api again, I go through the install process again. It doesn't reinstall but it starts a valid session.

**Comment by junaid33** [comment]
Yep faced this same issue. In the shopifyAuth({}) function, add
   `accessMode: "offline"`
This will have the token work longer, but I believe you will still have refresh it.

**Comment by letsbelopez** [comment]
Thanks for all the help. Do you plan to keep working on this project? It looks like Shopify have been working on their app development projects a lot lately. I'm curious how it's going to go.
